In [9]:
import pandas as pd
import numpy as np
# In[2]:
wd = pd.read_csv('winequalityN.csv')
# In[3]:
wd.head(5)
# In[4]:
print(f'Number of empty records: {wd.isna().sum().sum()}')
# In[5]:
wd.dropna(inplace=True)
# In[6]:
wd_des = wd.describe()
# In[7]:
for i in wd_des.columns:
  if wd_des[i]['mean']!=0 or wd_des[i]['std']!=1 :
    print('standardization needed in ',i)
    
# In[8]:
X = wd.iloc[:,:-1].values
y = wd.iloc[:,-1].values
display("X values ",X[0])
print('Y values ',y)
# In[9]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder',OneHotEncoder(),[0])],remainder
= 'passthrough')
print(ct)
X = np.array(ct.fit_transform(X))
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
X = ss.fit_transform(X)
# In[11]:
df=pd.DataFrame(X,columns=wd.columns)
display(df)
df.describe()

Number of empty records: 38
standardization needed in  fixed acidity
standardization needed in  volatile acidity
standardization needed in  citric acid
standardization needed in  residual sugar
standardization needed in  chlorides
standardization needed in  free sulfur dioxide
standardization needed in  total sulfur dioxide
standardization needed in  density
standardization needed in  pH
standardization needed in  sulphates
standardization needed in  alcohol
standardization needed in  quality

'X values '

array(['white', 7.0, 0.27, 0.36, 20.7, 0.045, 45.0, 170.0, 1.001, 3.0,
       0.45, 8.8], dtype=object)

Y values  [6 6 6 ... 6 5 6]
ColumnTransformer(remainder='passthrough',
                  transformers=[('encoder', OneHotEncoder(), [0])])

,type,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,-0.571931,0.571931,-0.167786,-0.422710,0.283959,3.207420,-0.315228,0.815609,0.960779,2.099926,-1.359160,-0.544987,-1.418922
1,-0.571931,0.571931,-0.707155,-0.240479,0.146257,-0.808151,-0.201180,-0.930138,0.288479,-0.232465,0.508399,-0.276354,-0.832184
2,-0.571931,0.571931,0.679794,-0.361966,0.559363,0.306117,-0.172668,-0.029107,-0.330745,0.134053,0.259391,-0.612146,-0.329265
3,-0.571931,0.571931,-0.013681,-0.665684,0.008554,0.642500,0.055427,0.928238,1.243853,0.300653,-0.176373,-0.880779,-0.496905
4,-0.571931,0.571931,-0.013681,-0.665684,0.008554,0.642500,0.055427,0.928238,1.243853,0.300653,-0.176373,-0.880779,-0.496905
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6458,1.748464,-1.748464,-0.321892,1.703315,-1.643871,-0.745079,0.340545,-0.141736,-1.374580,0.603864,1.255423,1.939871,-0.832184
6459,1.748464,-1.748464,-0.784208,1.581828,-1.643871,-0.724055,0.967807,0.083522,-1.268427,0.067414,1.442179,0.328071,0.006014
6460,1.748464,-1.748464,-0.707155,1.035136,-1.299616,-0.660984,0.568640,-0.085421,-1.339195,0.347301,1.255423,1.469762,0.425113
6461,1.748464,-1.748464,-1.015366,1.855174,-1.368467,-0.724055,0.540129,0.083522,-1.268427,0.257337,2.189203,1.201129,-0.245446
6462,1.748464,-1.748464,-0.938313,-0.179735,1.041320,-0.387673,0.312034,-0.704880,-1.303811,0.264001,1.068667,0.865337,0.425113

,type,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
count,6.463000e+03,6.463000e+03,6.463000e+03,6.463000e+03,6.463000e+03,6.463000e+03,6.463000e+03,6.463000e+03,6.463000e+03,6.463000e+03,6.463000e+03,6.463000e+03,6.463000e+03
mean,-1.407233e-16,1.055425e-16,1.085328e-14,-1.266510e-15,3.854059e-14,-4.679050e-15,-6.596405e-15,-7.036165e-17,1.055425e-16,1.642883e-12,2.030813e-14,-9.534004e-15,-4.372097e-14
std,1.000077e+00,1.000077e+00,1.000077e+00,1.000077e+00,1.000077e+00,1.000077e+00,1.000077e+00,1.000077e+00,1.000077e+00,1.000077e+00,1.000077e+00,1.000077e+00,1.000077e+00
min,-5.719307e-01,-1.748464e+00,-2.633473e+00,-1.576837e+00,-2.194680e+00,-1.018391e+00,-1.341655e+00,-1.662225e+00,-1.940727e+00,-2.528205e+00,-3.102215e+00,-2.089628e+00,-2.089480e+00
25%,-5.719307e-01,5.719307e-01,-6.301024e-01,-6.656838e-01,-4.734030e-01,-7.661033e-01,-5.148107e-01,-7.611944e-01,-6.845873e-01,-7.889073e-01,-6.743884e-01,-6.793038e-01,-8.321839e-01
50%,-5.719307e-01,5.719307e-01,-1.677861e-01,-3.012225e-01,-6.029661e-02,-5.138161e-01,-2.582038e-01,-8.542138e-02,4.078931e-02,6.408161e-02,-5.186862e-02,-1.420373e-01,-1.616257e-01
75%,-5.719307e-01,5.719307e-01,3.715830e-01,3.669567e-01,4.905119e-01,5.584045e-01,2.550099e-01,5.903516e-01,7.130896e-01,7.671311e-01,6.329031e-01,4.623876e-01,6.765720e-01
max,1.748464e+00,5.719307e-01,6.689906e+00,7.534697e+00,9.234597e+00,1.268921e+01,1.582249e+01,1.455633e+01,5.737650e+00,1.475482e+01,4.928289e+00,9.864552e+00,3.694084e+00